# reusable action
name: "Get latest tag"
description: "Get the latest release tag"
runs:
  using: "composite"
  steps:
    - name: Get latest Vinyl release tag
      id: step_getlatest_tag
      run: |
        # get latest release tag from remote
        latest_tag=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags $REPOSITORY '*.*' \
                      | tail --lines=1 | cut --delimiter='/' --fields=3)

        echo "INFO: Latest tag = $latest_tag"
        test ! -z "$latest_tag" && echo "LATEST_TAG=$latest_tag" >> "$GITHUB_ENV" \
        || echo "ERROR: Latest tag not found" || exit 1

      shell: bash
