name: Build Vinyl Theme

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add KDE Neon Repositories and GPG Key
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          echo "deb http://archive.neon.kde.org/user noble main" | sudo tee /etc/apt/sources.list.d/kde-neon.list
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE6D4736255751E5D' | sudo tee /etc/apt/keyrings/neon-key.asc
          echo "deb [signed-by=/etc/apt/keyrings/neon-key.asc] http://archive.neon.kde.org/user noble main" | sudo tee /etc/apt/sources.list.d/kde-neon.list
          sudo apt update

      - name: Install dependencies
        run: |
          sudo apt install -y \
            git build-essential cmake extra-cmake-modules \
            kf6-frameworkintegration-dev kf6-kcmutils-dev \
            kf6-kcolorscheme-dev kf6-kconfig-dev kf6-kconfigwidgets-dev \
            kf6-kcoreaddons-dev kf6-kguiaddons-dev kf6-ki18n-dev \
            kf6-kiconthemes-dev kf6-kirigami2-dev kf6-kpackage-dev \
            kf6-kservice-dev kf6-kwindowsystem-dev \
            libx11-dev libplasma-dev qt6-base-dev \
            qt6-declarative-dev qtbase5-dev qtdeclarative5-dev gettext \
            qt6-svg-dev qt3d5-dev inkscape unzip x11-apps \
            libkdecorations3-dev

      - name: Fix script permissions and use Bash
        run: |
          chmod +x icons/make-theme.sh
          sed -i '1s|^.*$|#!/bin/bash|' icons/make-theme.sh

      - name: Build Vinyl Theme
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Upload compiled theme
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: vinyl-theme
          path: build/
