name: Build Vinyl Theme

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add KDE Neon Repositories
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y "deb http://archive.neon.kde.org/user noble main"
          sudo apt update

      - name: Install dependencies
        run: |
          sudo apt install -y \
            git build-essential cmake extra-cmake-modules \
            kf6-frameworkintegration-dev kf6-kcmutils-dev \
            kf6-kcolorscheme-dev kf6-kconfig-dev kf6-kconfigwidgets-dev \
            kf6-kcoreaddons-dev kf6-kguiaddons-dev kf6-ki18n-dev \
            kf6-kiconthemes-dev kf6-kirigami2-dev kf6-kpackage-dev \
            kf6-kservice-dev kf6-kwindowsystem-dev \
            libx11-dev libkdecorations2-dev libplasma-dev qt6-base-dev \
            qt6-declarative-dev qtbase5-dev qtdeclarative5-dev gettext \
            qt6-svg-dev qt3d5-dev inkscape unzip x11-apps

      - name: Build Vinyl Theme
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
